### ISSUE TITLE
如何支持h264的裸流播放？

### ISSUE THREAD

**Issue by luanwulin** [qiaozi-tech/WXInlinePlayer#11]
在摄像头公司，拿到的是rtsp的h264流，需要修改哪里才能支持播放呢？

**Comment by ErosZy** [comment]
@luanwulin 既然你是h264流，那么可以忽略掉flv的demux，这个需要参考https://github.com/qiaozi-tech/WXInlinePlayer/tree/master/lib/codec/src这块的代码。

**Comment by luanwulin** [comment]
@ErosZy 需要修改c的代码，去掉demux流程么？

**Comment by ErosZy** [comment]
对的

> @ErosZy 需要修改c的代码，去掉demux流程么？
