### ISSUE TITLE
直播延时会越来越大

### ISSUE THREAD

**Issue by ouzhou** [qiaozi-tech/WXInlinePlayer#13]
试了一下，刚开始3s左右然后越来越大 到了后面快10s延时了，有没有什么机制能减少这样的情况

**Comment by ErosZy** [comment]
> 试了一下，刚开始3s左右然后越来越大 到了后面快10s延时了，有没有什么机制能减少这样的情况

先认真阅读文档：https://github.com/qiaozi-tech/WXInlinePlayer#%E5%A6%82%E4%BD%95%E9%99%8D%E4%BD%8E%E5%8D%A1%E9%A1%BF%E5%92%8C%E5%BB%B6%E8%BF%9F

如果还不行，给出一个稳定的复现地址。

**Comment by ErosZy** [comment]
if you have any questions, please reopen this issue.
