### ISSUE TITLE
套在iframe内无法使用

### ISSUE THREAD

**Issue by ouzhou** [qiaozi-tech/WXInlinePlayer#14]
example在pc和手机微信都能播放flv，是正常的。
嵌套在iframe里面，pc端可以正常播放，但是在手机的浏览器里面，js也没有报错，但是无法播放
不太明白为什么，感觉是手机的iframe会阉割掉某些功能，关键是没有任何报错信息，没办法debug

**Comment by ouzhou** [comment]
场景是这样的，我们想在微信小程序里面用flv直播，但是小程序原生的player不支持http-flv，然后我就想通过小程序的webview加载一个网页，在这个网页里面用flv。
为了测试是否可用，我先测微信的网页（网页，非小程序），结果发现，单独用这个能直播，但是嵌套在ifrme里面打开就无法直播了

**Comment by ErosZy** [comment]
@ouzhou 能提供一个复现的url么？

**Comment by ouzhou** [comment]
@ErosZy 奥 小程序支持flv和rtmp，
复现很简单，把那个产出的文件夹serve出去，然后搞一个简单的html，在html里面用iframe套地址，在手机微信是无法使用的，当时直接访问手机微信可以使用

**Comment by ErosZy** [comment]
@ouzhou 建议使用小程序原生的播放器，他会有更多的适配和优化，性能也会更好。
