### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by nd0164** [qiaozi-tech/WXInlinePlayer#15]
when i try to complie the baseline version， on ubuntu 19.10

i got this error，on obj link: 

`wasm-ld: error: /xxx/WXInlinePlayer/lib/codec/3rdparty/openh264/libopenh264wasm.so: machine type must be wasm32`

**Comment by ErosZy** [comment]
请切换到emscripten 1.38.45版本

**Comment by nd0164** [comment]
thanks! it work!

**Comment by leoyao0613** [comment]
> [Chinese] 请切换到emscripten 1.38.45版本 [English] please change emscripten to 1.38.45 version.

请问如果要用2..0以上版本，需要做哪些方面的修改才能编译通过？ 谢谢

**Comment by leoyao0613** [comment]
> [Chinese] 请切换到emscripten 1.38.45版本 [English] please change emscripten to 1.38.45 version.

请问如果要用em 2.0以上版本，需要做哪些方面的修改才能编译通过？ 麻烦指点，谢谢了
