### ISSUE TITLE
如何拿到解码后的mp4的video对象？

### ISSUE THREAD

**Issue by ouzhou** [qiaozi-tech/WXInlinePlayer#16]
我在做一个360度全景直播播放器，现在只要拿到解码后的blob或者video对象，把它作为video texture放在threejs下面我就能实现全景直播了，希望大佬指路，在什么地方获取到这个flv解码后的video

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/76002777-14d1de80-5f42-11ea-9582-833144fff4ce.png)
是这个吗

**Comment by ouzhou** [comment]
![image](https://user-images.githubusercontent.com/7693866/76002860-2dda8f80-5f42-11ea-9d12-e40c60badf9c.png)
是这个吗

**Comment by ouzhou** [comment]
我刚开始理解的是为了防止音画不同步，所以这个是通过解析flv为mp4，但是大概看了一下 ，好像是通过processor调用frame然后用gl在shader上绘制， 并没有正常的mp4数据

**Comment by ErosZy** [comment]
这个项目是WASM软解flv实现自己的绘制和音频播放，跟MP4没关系。
你说的360全景播放我不是特别了解，如果你要拿到帧数据，请参考这里：https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/src/processor/processor.js#L380
