### ISSUE TITLE
同一flv直播流，Android正常，iOS端画音不同步

### ISSUE THREAD

**Issue by ForeverHYH** [qiaozi-tech/WXInlinePlayer#18]
使用同一个flv直播流进行测试，走默认配置，Android端播放正常，iOS端音频比画面要慢0.5s左右。
请问这里有什么办法优化吗？

**Comment by ErosZy** [comment]
iOS版本是多少？使用的浏览器及其版本是什么？有测试文件或者直播流么？

**Comment by ForeverHYH** [comment]
iOS机11和XS
系统 13.3.1 
微信最新版（7.0.12）及自带Safari两端测试
打开提供的demo地址播放默认流（https://static.petera.cn/music.flv）
声音会比画面慢，Android及pc chrome打开对比正常

**Comment by ErosZy** [comment]
thx. 我试着复现一下。

**Comment by ForeverHYH** [comment]
好像发现规律了：iOS端解码音频的时候，也就是_onDecodeSuccess这里面，第二段音频每次都会包含第一段音频。所以导致第一段音频重复播放了两次，至于为什么会出现这种情况还需要麻烦作者大大帮忙看下iOS端在音频解码部分是否有什么问题（不是很懂C
我这边目前临时的解决方案是记录iOS端的第一段音频的时长，在audioSrc.start播放时减去第一段时长，相当于音频时间轴向前偏移第一段音频时长的长度，就能保证画音同步了

**Comment by ErosZy** [comment]
> 好像发现规律了：iOS端解码音频的时候，也就是_onDecodeSuccess这里面，第二段音频每次都会包含第一段音频。所以导致第一段音频重复播放了两次，至于为什么会出现这种情况还需要麻烦作者大大帮忙看下iOS端在音频解码部分是否有什么问题（不是很懂C
> 我这边目前临时的解决方案是记录iOS端的第一段音频的时长，在audioSrc.start播放时减去第一段时长，相当于音频时间轴向前偏移第一段音频时长的长度，就能保证画音同步了

谢谢。
