### ISSUE TITLE
通过demo测试，flv直播流视频静默状态（推流时视频mute），延迟较高

### ISSUE THREAD

**Issue by vincent-cihan** [qiaozi-tech/WXInlinePlayer#19]
您好，通过您的demo测试，默认配置，flv直播流在视频静默状态（视频黑屏，音频正常时）延迟较高，大概8～15秒，测试设备：macbook pro和iPhone 6s。其中MacBook上，解码能力：解码平均：289ms, 单元平均：6883ms。
当视频打开，音频也正常时，延迟好的多，大概4秒以上，不过音频略有0.5秒延迟。MacBook上，解码ms下降，解码平均：53ms, 单元平均：870ms

**Comment by ErosZy** [comment]
@vincent-cihan 能提供复现的直播FLV流么？
