### ISSUE TITLE
视频转换问题，有声音无画面

### ISSUE THREAD

**Issue by gto999** [qiaozi-tech/WXInlinePlayer#2]
![企业微信截图_15650623604034](https://user-images.githubusercontent.com/8032538/62509481-f2f26b00-b83d-11e9-9d38-29994316906a.png)

**Comment by ErosZy** [comment]
高版本Chrome浏览器为了用户体验，需要用户主动点击才能出声音。在代码里请监听playtimeout事件，查看是否触发。

PS: 你的分辨率1080P的话，中端手机可能渲染吃力，建议推荐720P或者360p。

**Comment by ErosZy** [comment]
@gto999 现已支持1080P视频文件的播放，但是解码吃力，所以还是请降级到720P

**Comment by RomeoAndJulietAndMe** [comment]
您好这位兄弟，bash build.sh你的报错吗
