### ISSUE TITLE
使用Node-Media-Server搭建的流媒体服务器 播放的时候声音正常 视频不正常播放

### ISSUE THREAD

**Issue by zhouqiang93** [qiaozi-tech/WXInlinePlayer#21]
Node-Media-Server项目网址：https://github.com/illuspas/Node-Media-Server/
推流至腾讯云平台，用WXInlinePlayer，播放没有问题，不过用Node-Media-Server，却出现声音正常播放，视频只显示加载第一张图片，就不动了，不知道是哪儿出现了问题

**Comment by ErosZy** [comment]
暂不考虑支持非主流流媒体服务。
