### ISSUE TITLE
ffmpeg mp4 转 flv 解码错误

### ISSUE THREAD

**Issue by ZhaoCSS** [qiaozi-tech/WXInlinePlayer#22]
Uncaught (in promise) RangeError: Invalid array buffer length
    at new SharedArrayBuffer (<anonymous>)

**Comment by ZhaoCSS** [comment]
这是视频参数
Metadata:
    major_brand     : isom
    minor_version   : 512
    compatible_brands: isomiso2avc1mp41
    encoder         : Lavf58.20.100
  Duration: 00:31:04.28, start: 0.055000, bitrate: 334 kb/s
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 848x478 [SAR 478:477 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc
    Stream #0:1: Audio: mp3, 44100 Hz, stereo, fltp, 128 kb/s

**Comment by ErosZy** [comment]
请提供源文件或者地址。

**Comment by ZhaoCSS** [comment]
https://v002.1d1d100.com/6.flv

**Comment by ErosZy** [comment]
无法访问

**Comment by ZhaoCSS** [comment]
再试试这个链接

**Comment by ErosZy** [comment]
0. 需要起一个本地服务，比如npm里的static-server
1. 代码中的url路径请写完整路径，例如本地测试请写：http://localhost:9080/6.flv
2. 你的视频的video frame存在openh264无法接码的部分，需要转一次码：
ffmpeg -i 6.flv -c:a copy -c:v libx264-profile:v baseline out.flv

**Comment by ZhaoCSS** [comment]
谢谢
