### ISSUE TITLE
这个产品是如何防止被各个厂商劫持 video 标签的，可以介绍下吗？

### ISSUE THREAD

**Issue by lizy0329** [qiaozi-tech/WXInlinePlayer#24]
特别是自动播放功能

**Comment by ErosZy** [comment]
通过wasm进行软解flv获取音频及视频，然后音画同步进行播放。

**Comment by lizy0329** [comment]
> 通过wasm进行软解flv获取音频及视频，然后音画同步进行播放。

播放不是需要 video 标签或者 Canvas 么？浏览器厂商正式劫持了这两个东西，那真的能够其作用吗？

**Comment by ErosZy** [comment]
> > 通过wasm进行软解flv获取音频及视频，然后音画同步进行播放。
> 
> 播放不是需要 video 标签或者 Canvas 么？浏览器厂商正是劫持了这两个东西，那真的能够其作用吗？

浏览器不会阉割canvas，只会阉割或者劫持video
