### ISSUE TITLE
stream.js这段代码 经常会出现  endIndex - startIndex <0的情况 然后报错

### ISSUE THREAD

**Issue by bondzasd** [qiaozi-tech/WXInlinePlayer#26]
stream.js这段代码 function slice(buffer, startIndex, endIndex) 这个函数里 经常会出现 (endIndex - startIndex)<0 的情况 然后报错StreamLoader.read 请问怎么解决 截图已经发您qq了

**Comment by xd11223** [comment]
StreamLoader.prototype._getChunk的data.length < chunkSize發生的問題，加個判斷data.length > this.chunkSize就可以解決了。

**Comment by ErosZy** [comment]
可以提供PR或者之后有空会进行修复。

**Comment by ErosZy** [comment]
@bondzasd 已修复。
