### ISSUE TITLE
播放视频有声音的时候会报这个错， 但不影响视频播放 和音频播放

### ISSUE THREAD

**Issue by bondzasd** [qiaozi-tech/WXInlinePlayer#28]
Uncaught (in promise) DOMException: Unable to decode audio data

播放视频有声音的时候会报这个错， 但不影响视频播放 和音频播放

**Comment by xd11223** [comment]
會出現這錯誤應該是網路不穩，沒有給Web Audio API一個sample所以無法decode。

**Comment by ErosZy** [comment]
> 會出現這錯誤應該是網路不穩，沒有給Web Audio API一個sample所以無法decode。

感谢回答。

**Comment by bondzasd** [comment]
> 會出現這錯誤應該是網路不穩，沒有給Web Audio API一個sample所以無法decode。

请问怎么解决呢？

**Comment by ErosZy** [comment]
https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/src/processor/processor.js#L439

增大此处的splice值，但是会造成起播更慢。

**Comment by xd11223** [comment]
> https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/src/processor/processor.js#L439
> 
> 增大此处的splice值，但是会造成起播更慢。

https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/src/processor/processor.js#L441
這邊也會需要判斷this.audio.length的大小，確認有多少個sample才去做decodeAudioData。
