### ISSUE TITLE
按照案例运行后没有任何反应

### ISSUE THREAD

**Issue by qq1002158476** [qiaozi-tech/WXInlinePlayer#3]
谷歌浏览器，开启了自动播放，下载的是zip，解压后，放到xampp
服务器环境下，新建index.html 写完后运行，没有任何效果，flv用的是下载时自带的

**Comment by ErosZy** [comment]
请查看控制台，贴出报错信息。

**Comment by huangxiaojia** [comment]
我也是一样的情况，控制台没有报错信息

**Comment by ErosZy** [comment]
> 我也是一样的情况，控制台没有报错信息

可以把对应代码和视频文件发我邮箱zyeros1991@gmail.com

**Comment by ErosZy** [comment]
@huangxiaojia @qq1002158476 示例代码已修复，示例代码为了说明api，在play事件里面进行了stop操作。
