### ISSUE TITLE
有考虑只提供解码器，分离开播放视频的渲染部分吗

### ISSUE THREAD

**Issue by ouzhou** [qiaozi-tech/WXInlinePlayer#30]
目前播放这一块没有UI，不如直接分成两个项目，一个是解码器，一个是视频播放器UI，这样可以更有拓展性
有了这样的拓展，就能很方便实现类似与360全景直播视频，目前我魔改了源码，禁用掉了渲染webgl的部分，直接拿frame的数据去做了一个全景直播播放器，后面会考虑提供PR

**Comment by ErosZy** [comment]
目前没有精力维护项目，后面提供PR的话就非常感谢了。
