### ISSUE TITLE
h265解码无效

### ISSUE THREAD

**Issue by ouzhou** [qiaozi-tech/WXInlinePlayer#31]
流媒体用的
https://github.com/xiongziliang/ZLMediaKit
推流用的金山的FFmpeg3.4 patch,可以推，ffplay也可以播265，但是用这个网页播放器无法播

复现步骤
1 使用docker 跑一个ZLMediaKit流媒体服务
docker run -id -p 1935:1935 -p 8080:80 gemfield/zlmediakit:20.04-runtime-ubuntu18.04
2 使用金山ffmpeg推流265
3 使用金山ffplay播放
4 使用wxinlineplayer播放

**Comment by ErosZy** [comment]
请直接提供可使用的流或者媒体文件，环境搭建太浪费时间了。

**Comment by bondzasd** [comment]
我这里 用大牛sdk 推h265的 flv流 可以播放 没有问题

**Comment by ouzhou** [comment]
@ErosZy 
推流
rtmp://39.106.216.132:1935/live/ouzz
播放
http://39.106.216.132:8080/live/ouzz.flv

**Comment by ouzhou** [comment]
@bondzasd 流媒体服务器用的哪一家的，sdk的链接能发一个吗

**Comment by ErosZy** [comment]
> http://39.106.216.132:8080/live/ouzz.flv

我这里访问404了。

**Comment by ouzhou** [comment]
你先用obs试试 我刚测了是可以的

**Comment by ErosZy** [comment]
> 你先用obs试试 我刚测了是可以的

我obs也不行，能给一个10s的可播放片段么？

**Comment by ouzhou** [comment]
因为我没有推，，我以为你要推流

**Comment by ErosZy** [comment]
最好给我个片段或者H265的流吧，我机器上没有相关的推流环境。

**Comment by ouzhou** [comment]
好的
你断掉 我来推

**Comment by ouzhou** [comment]
推出来了，我用ffplay是可以播放的 但是用wxinlineplayer就不行，确实是265的

**Comment by ErosZy** [comment]
> 推出来了，我用ffplay是可以播放的 但是用wxinlineplayer就不行，确实是265的

解码失败了，我截取个片段，然后本地查一下。

**Comment by ouzhou** [comment]
我微信ouzz413

**Comment by ouzhou** [comment]
我刚把流媒体换成了腾讯云的直播服务，就可以播了，感觉是流媒体服务器的问题

**Comment by ErosZy** [comment]
> 我刚把流媒体换成了腾讯云的直播服务，就可以播了，感觉是流媒体服务器的问题

这个要查一下解码，我家里没有C++的环境，只能明天才能看看原因。
如果你熟悉C++并且有对应的环境，你可以打开本地媒体文件读取：https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/lib/codec/src/main.cpp#L104
然后执行看一下报错，应该很快能找到问题。

截取的文件：https://static.petera.cn/h265_decode_error.flv

**Comment by ouzhou** [comment]
奥 说错了，我看了一些文档，说的腾讯云会默认把265的又转回264，只是没想到用265的js居然也能播放264的flv流

**Comment by ErosZy** [comment]
> 奥 说错了，我看了一些文档，说的腾讯云会默认把265的又转回264，只是没想到用265的js居然也能播放264的flv流

如果着急你们可以自己排查一下，如果不着急，我明天查了原因来close这个issue

**Comment by ouzhou** [comment]
你们用的自研的流媒体服务还是云服务呢

**Comment by ErosZy** [comment]
> 你们用的自研的流媒体服务还是云服务呢

你的推流截取的文件从C++运行来看，codecId=12确实是金山的标准，但是libde265无法解码你的流获得图像信息。怀疑你推的h265的流不被libde265支持。

**Comment by ErosZy** [comment]
@ouzhou 已修复，PPS丢失问题，请使用example最新编译的版本
