### ISSUE TITLE
ios10和11上运行示例，load success后继续执行出错："TypeError: Value is not a sequence" on Safari of ios10 and ios11 

### ISSUE THREAD

**Issue by Susy123** [qiaozi-tech/WXInlinePlayer#35]
在ios10和ios11的safari上运行示例https://qiaozi-tech.github.io/WXInlinePlayer/example/index.html；load success后抛出错误"TypeError: Value is not a sequence"，不能正常播放。
![image](https://user-images.githubusercontent.com/17647877/88052824-6c898300-cb8d-11ea-857e-07435f41ab12.png)

**Comment by ErosZy** [comment]
手上的机器没有问题，有error stack么？截图截全一点。

**Comment by Firstnote** [comment]
同样的问题，在index中 this.emit("mediaInfo", t.data)之后，另一个进程的onmessage触发时会报这个错

**Comment by Susy123** [comment]
browserstack上这个测试过可以复现问题。
![image](https://user-images.githubusercontent.com/17647877/88127451-36d4b080-cc06-11ea-8da5-ebd51ad9ce96.png)

**Comment by ErosZy** [comment]
will fixed in 1.3.3

**Comment by Susy123** [comment]
请求提示一下大致思路，🤣尝试本地先修复用一下 @ErosZy

**Comment by ErosZy** [comment]
@Susy123 从报错来看我猜测是postMessage造成的，比较可疑的是在这里：
https://github.com/qiaozi-tech/WXInlinePlayer/blob/master/src/loader/stream.js#L175

**Comment by Susy123** [comment]
调试了一下，问题确实出在postMessage，第二个参数在ios10和11上不支持null，换成undefined即可；位置在：
https://github.com/qiaozi-tech/WXInlinePlayer/blob/1ce82c59b408c8e5feb06fdb48a4002bda2aa8bb/lib/codec/combine/glue.js#L139

https://github.com/qiaozi-tech/WXInlinePlayer/blob/1ce82c59b408c8e5feb06fdb48a4002bda2aa8bb/lib/codec/combine/glue.js#L97

![image](https://user-images.githubusercontent.com/17647877/88366916-06834280-cdbd-11ea-9217-7d15b5a222fa.png)

（感谢 @Firstnote 协同定位修复问题）

**Comment by ErosZy** [comment]
@Susy123 可以提个PR么？
