### ISSUE TITLE
iOS  同时直播6路视频，只有4路成功。

### ISSUE THREAD

**Issue by ArcoMu** [qiaozi-tech/WXInlinePlayer#36]
IOS 上 6个canvas 同时直播6路视频，只有4路成功加载。 同一页面安卓上运行良好。测试手机：iphone11 ，版本是13.5.1， 华为P20Pro 微信最新版。测试URL：http://183.233.190.23:6061/tmp/WXInlinePlayer-example/demo183.html

**Comment by ErosZy** [comment]
有报错信息提供么？

**Comment by ArcoMu** [comment]
![image](https://user-images.githubusercontent.com/20966750/88128268-27eefd80-cc08-11ea-896f-2e53baf0e7fb.png) 麻烦看下，谢谢

**Comment by ErosZy** [comment]
这块看起来是音频那边引起的，不确定iOS是不是有限制，如果你是监控没有声音输出，把hasAudio设置为fasle看看

**Comment by ArcoMu** [comment]
![image](https://user-images.githubusercontent.com/20966750/88139880-326ac080-cc23-11ea-8ba3-8a784ddbe9bb.png)
禁用了，也是不行

**Comment by ArcoMu** [comment]
我写了另外一个DEMO，点播6路flv视频（网上找的，带音频。应该是标准的），也是只有4路正常，在Mac和IOS上。应该可以排除我的flv流问题（有音频的），应该是苹果的限制。有没方法去work around?

**Comment by ErosZy** [comment]
如果是监控，那么推流的时候去掉音频流，然后在调用时设置hasAudio=fasle，这样就不会强制和音频同步

**Comment by ArcoMu** [comment]
我尝试了：用ffmeg去掉flv文件的音频，点播6路，依然不行。感觉有没音频都会触发那个异常。

**Comment by ErosZy** [comment]
@ArcoMu 贴一下ffmpeg的flv信息。

**Comment by ArcoMu** [comment]
![image](https://user-images.githubusercontent.com/20966750/88363485-cb7c1180-cdb2-11ea-9b57-b78708fa8189.png)
![image](https://user-images.githubusercontent.com/20966750/88363530-f36b7500-cdb2-11ea-9e89-fc5ba1fc1366.png)
我用的转换命令是`ffmpeg  -i zghhr.flv  -map 0:0   -vcodec copy -acodec copy out.flv`

**Comment by ErosZy** [comment]
@ArcoMu 那我有点怀疑是Worker的创建限制，因为你剩余两个流并没有打印加载成功的消息。但是最近我没太多时间，你可以自己排查一下。

**Comment by ArcoMu** [comment]
> @ArcoMu 那我有点怀疑是Worker的创建限制，因为你剩余两个流并没有打印加载成功的消息。但是最近我没太多时间，你可以自己排查一下。
我得首先借台mac才行，我尽力吧。你有空也改下吧

**Comment by ErosZy** [comment]
@ArcoMu iOS限制了AudioContext的创建，超过4个后返回null，造成报错。同时，也限制了Worker的数量，过多的Worker不会进行对应的初始化操作。系统限制，没有太好的办法绕过。

**Comment by ErosZy** [comment]
```javascript
// 超过4个AudioContext则报错
for(let i = 0; i < 6; i++){
   const ctx = new AudioContext();
   const gainNode = ctx .createGain();
   gainNode.gain.value = 0.0;
   gainNode.connect(ctx.destination);
}
```
