### ISSUE TITLE
主播每说一句话  后面会夹杂轻微的电流声

### ISSUE THREAD

**Issue by bondzasd** [qiaozi-tech/WXInlinePlayer#39]
如果直播 采集主播的 说话声音 ，主播每说一句话  后面会夹杂轻微的电流声。用vlc 等其他软件播同样的流 没有电流声 。证明应该不是推流端和流媒体服务器的问题。
请问有解决办法吗?

**Comment by ErosZy** [comment]
调大chunkSize，电流声是因为audio context连接播放造成的。目前浏览器不支持live stream的audio context，因此会有此类问题。

**Comment by xd11223** [comment]
ㄝ這問題就只能等web audio v2 或是web codecs出來了，如果用音頻是aac，用audioworklet會減緩一點。
