### ISSUE TITLE
使用的是flv 格式的 ，报错：not support this video type(only AVC support)求解

### ISSUE THREAD

**Issue by huangxiaojia** [qiaozi-tech/WXInlinePlayer#4]
![](https://user-images.githubusercontent.com/14231703/62694893-cd18c200-ba07-11e9-92af-a3361e2bbbb2.png)

**Comment by huangxiaojia** [comment]
![image](https://user-images.githubusercontent.com/14231703/62694893-cd18c200-ba07-11e9-92af-a3361e2bbbb2.png)

**Comment by ErosZy** [comment]
只支持AVC，请使用ffmpeg进行转码：
```shell
ffmpeg -i <your file> -vcodec h264 -acodec aac -profile:v baseline output.flv
```

**Comment by ErosZy** [comment]
只支持AVC，请使用ffmpeg进行转码：
