### ISSUE TITLE
ios上开启静音键后，直播播放无声

### ISSUE THREAD

**Issue by HeGangSZ** [qiaozi-tech/WXInlinePlayer#45]
机型：iphone7
系统版本：ios13.5.1
表现：开启侧边的静音键后，直播画面无声，audio或video标签原生支持的播放这时候是有声音的，难道audio-context被苹果认为是铃声了？

反馈现象和这个帖子一样：https://www.jackpu.com/ios-12-jing-yin-mo-shi-xia-audiocontext-wu-fa-zheng-chang-bo-fang-de-bug/

**Comment by ErosZy** [comment]
在iOS的Slient Mode模式下，是禁止AudioContext的声音播放的，这是iOS的feature，原因是为了修复之前Webkit可以被通过AudioContext绕过Media Policy（点击自动播放）的问题。后来他们就没有再还原了。
