### ISSUE TITLE
vue-cli3.0创建的SPA程序中流加载成功，但canvas无法正确刷新显示

### ISSUE THREAD

**Issue by ArcoMu** [qiaozi-tech/WXInlinePlayer#47]
![image](https://user-images.githubusercontent.com/20966750/90479089-b8195780-e160-11ea-92ab-2675b51f26ba.png)
![image](https://user-images.githubusercontent.com/20966750/90479117-c1a2bf80-e160-11ea-8165-dcf2c9545b82.png)
![image](https://user-images.githubusercontent.com/20966750/90479167-d3846280-e160-11ea-82c4-caddf80ce6b5.png)
![image](https://user-images.githubusercontent.com/20966750/90479283-fe6eb680-e160-11ea-8385-4ff504057687.png)
![image](https://user-images.githubusercontent.com/20966750/90479334-18a89480-e161-11ea-84c5-8ddf5af91a7f.png)

测试URL：http://183.233.190.23:6061/tmp/WebClient/#/
请问库现在是不是对webpack支持不够友好？用vue-cli3.0的SPA程序中canvas无法正确刷新显示，看网络打印，流是加载成功了的，也打印了`load success`，但是canvas仍然保持默认的gray颜色

**Comment by ArcoMu** [comment]
![image](https://user-images.githubusercontent.com/20966750/90479569-76d57780-e161-11ea-9009-4a0f2c5eb1d9.png)
补充图片

**Comment by ErosZy** [comment]
没维护wx-inline-player-new这个npm库，可能需要去问这个包的作者。

**Comment by ArcoMu** [comment]
有考虑出个官方的npm的库么？

**Comment by coffe1891** [comment]
> 有考虑出个官方的npm的库么？

试试https://github.com/coffe1891/videojs-flvh265
wx-inline-player-new是我建的，C++代码一样，只是API不一样。

**Comment by ArcoMu** [comment]
谢谢。有个疑问，这个库需要使用到video标签，用canvas相对好点？
![image](https://user-images.githubusercontent.com/20966750/90596243-1dcd1880-e221-11ea-8e8c-dc2ffaa72623.png)

**Comment by coffe1891** [comment]
> 谢谢。有个疑问，这个库需要使用到video标签，用canvas相对好点？
> ![image](https://user-images.githubusercontent.com/20966750/90596243-1dcd1880-e221-11ea-8e8c-dc2ffaa72623.png)

用Video标签是为了兼容Video.js，因为你还可以用Video.js播放mp4什么的，但是当你用videojs-flvh265的时候，会将<video>标签替换成<canvas>，所以你的担心都是多余的。
