### ISSUE TITLE
花屏了

### ISSUE THREAD

**Issue by amhoho** [qiaozi-tech/WXInlinePlayer#5]
用安卓微信或QQhttps://h5.haohuimai1.com/#/ 能出声音 但花屏了 加载也卡得很

**Comment by amhoho** [comment]
再报一个,用示例代码运行.报错了.
```
Successfully compiled asm.js code (loaded from cache in 1ms)
传递给 decodeAudioData 的缓冲区包含一个未知的内容类型。
```

**Comment by ErosZy** [comment]
> 用安卓微信或QQhttps://h5.haohuimai1.com/#/ 能出声音 但花屏了 加载也卡得很

手机信息提供一下，方便判断。



> 再报一个,用示例代码运行.报错了.
> 
> ```
> Successfully compiled asm.js code (loaded from cache in 1ms)
> 传递给 decodeAudioData 的缓冲区包含一个未知的内容类型。
> ```

这种情况需要在catch里面进行页面降级。

**Comment by ErosZy** [comment]
> > 用安卓微信或QQhttps://h5.haohuimai1.com/#/ 能出声音 但花屏了 加载也卡得很
> 
> 手机信息/QQ以及微信版本提供一下，方便判断。
> 
> > 再报一个,用示例代码运行.报错了.
> > ```
> > Successfully compiled asm.js code (loaded from cache in 1ms)
> > 传递给 decodeAudioData 的缓冲区包含一个未知的内容类型。
> > ```
> 
> 这种情况需要在catch里面进行页面降级。

**Comment by amhoho** [comment]
录制了下面的动图:
![012](https://user-images.githubusercontent.com/24509574/63298922-3d2c1f80-c307-11e9-8861-091cfa915605.gif)

是在一个叫[雷电模拟器](https://www.ldmnq.com/)上的安卓模拟器测试的,很垃圾的模拟器,测试低配手机用的.
![02](https://user-images.githubusercontent.com/24509574/63298218-972be580-c305-11e9-8093-9148ad8d4f9d.jpg)
![03](https://user-images.githubusercontent.com/24509574/63298220-97c47c00-c305-11e9-956f-bf143fb4d6da.jpg)

**Comment by amhoho** [comment]
上面第二个报错是demo在pc端firefox或chrome都会出现的.

**Comment by ErosZy** [comment]
> 录制了下面的动图:
> ![012](https://user-images.githubusercontent.com/24509574/63298922-3d2c1f80-c307-11e9-8861-091cfa915605.gif)
> 
> 是在一个叫[雷电模拟器](https://www.ldmnq.com/)上的安卓模拟器测试的,很垃圾的模拟器,测试低配手机用的.
> ![02](https://user-images.githubusercontent.com/24509574/63298218-972be580-c305-11e9-8093-9148ad8d4f9d.jpg)
> ![03](https://user-images.githubusercontent.com/24509574/63298220-97c47c00-c305-11e9-956f-bf143fb4d6da.jpg)

模拟器对webgl支持不好，现在实际上可以选择降级到canvas 2d

**Comment by ErosZy** [comment]
> 上面第二个报错是demo在pc端firefox或chrome都会出现的.

模拟器对webgl支持不好，现在实际上可以选择降级到canvas 2d
第二个报错能提供一下chrome/firefox的版本么

**Comment by amhoho** [comment]
ff=v51,chrome=v76.0,请问目前支持http-flv或websocket-flv流视频么?比如直播常用的rtmp/flv/hls这样的流

**Comment by ErosZy** [comment]
> ff=v51,chrome=v76.0,请问目前支持http-flv或websocket-flv流视频么?比如直播常用的rtmp/flv/hls这样的流

目前不支持，但是现在在做新的重构（现在版本主要是符合我们自己的产品），估计9月中新版本出了就能覆盖到你们流式播放的需求。具体可以看TODO上面。

**Comment by amhoho** [comment]
感谢,期待!同时建议对上文动图那样的低端版机器bug修修,

**Comment by yimingjfe** [comment]
@amhoho  请问下好惠买平台在iOS端webview下自动播放是如何实现的？使用无音频的视频资源吗？
