### ISSUE TITLE
前端项目显示跨域

### ISSUE THREAD

**Issue by zzzzmayday** [qiaozi-tech/WXInlinePlayer#51]
你好，我在项目里尝试了一下，地址我先写死了一个ws的地址，控制台提示跨域了，请问是我哪里写的有问题吗，还是配置出错了，主要的代码就是以下的这段，同样的地址我用flvjs播是可以的
![image](https://user-images.githubusercontent.com/21163786/92689944-99c70600-f372-11ea-8714-e6bddcd2beab.png)
![image](https://user-images.githubusercontent.com/21163786/92689982-a9dee580-f372-11ea-9726-6335d4418eb2.png)

**Comment by ErosZy** [comment]
不支持websocket.
