### ISSUE TITLE
非常期待能支持http-flv或ws-flv,另建议搞个Q群,方便交流.

### ISSUE THREAD

**Issue by amhoho** [qiaozi-tech/WXInlinePlayer#7]
用今天的代码点播版ios没声音,而测试`http-flv`与`isLive:true`就报错`TypeError: t.body is undefined`
持续关注中,以期能解决ios中播放flv.

**Comment by ErosZy** [comment]
> 用今天的代码点播版ios没声音,而测试`http-flv`与`isLive:true`就报错`TypeError: t.body is undefined`
> 持续关注中,以期能解决ios中播放flv.

现以支持http-flv，flv现在只支持baseline。

**Comment by ErosZy** [comment]
@amhoho 请使用最新版本的all解码器进行尝试
