### ISSUE TITLE
播放摄像头实时流时只能显示部分画面，这是什么原因呢，急急急

### ISSUE THREAD

**Issue by zbmrtmp** [qiaozi-tech/WXInlinePlayer#87]
问题:推流设置分辨率是1280*720，用WXInlinePlayer拉流时发现**只能显示部分画面**，但是用vlc时可以正常显示，另外播放1280*720落地文件是可以正常播放得，只是会存在2.3秒得卡顿
当前进展:设置播放器尺寸大于1000*1000以上，也就是尺寸越大，显示得更小，甚至为1/10,小于1000*1000是显示1/3画面
当前代码:用得原生demo。 WXInlinePlayer.ready().then(()进入得是 player.on("loadSuccess", () ，没有进player.on("mediaInfo", (mediaInfo)，所以不知道流得具体尺寸
希望得到技术支持，万分感谢

**Comment by ErosZy** [comment]
please provide stream url or demo code.

**Comment by zbmrtmp** [comment]
> please provide stream url or demo code.

作者好！
我们是内网推流，所以无法提供，现发现在canvas 标签中设置和实时流一样得长宽就可以，但是不能自适应，有什么办法吗<canvas id="canvas" width="1280" height="720"></canvas>

**Comment by zbmrtmp** [comment]
> please provide stream url or demo code.
是这样设置的 <canvas id="canvas" width="1280" height="720"></canvas>

**Comment by ErosZy** [comment]
@zbmrtmp you can listen to `mediaInfo` event to get video's width and height to resize the canvas.

**Comment by ErosZy** [comment]
if you have other issues, plz reopen.
