### ISSUE TITLE
WebAssembly.Memory(): could not allocate memory     at TinyH264Codec.__TINY_H264_MAIN__

### ISSUE THREAD

**Issue by hoperyy** [qiaozi-tech/WXInlinePlayer#9]
![image](https://user-images.githubusercontent.com/5757051/64508430-00ed4d00-d310-11e9-8f7c-ef17d033d2f5.png)

init 多次后

**Comment by ErosZy** [comment]
这个报错看起来是因为存在多个实例，但没有被有效的释放，超过了内核的可使用Memory数量。

为了方便排查，请提供示例代码。

**Comment by hoperyy** [comment]
对，是多个实例，可以参考抖音短视频的交互那种，代码如下：

```js
new WXInlinePlayer({
                    url: this.videoList[index].video, // 仅支持flv格式(H264+AAC)
                    $container: document.getElementById('videoWrapper' + index),
                    volume: 1.0, // iOS不允许代码调节声量，请注意兼容
                    muted: false, // iOS和Android均支持代码控制静音
                    autoplay: false,
                    loop: true,
                });
            }
```

**Comment by ErosZy** [comment]
> 对，是多个实例，可以参考抖音短视频的交互那种，代码如下：
> 
> ```js
> new WXInlinePlayer({
>                     url: this.videoList[index].video, // 仅支持flv格式(H264+AAC)
>                     $container: document.getElementById('videoWrapper' + index),
>                     volume: 1.0, // iOS不允许代码调节声量，请注意兼容
>                     muted: false, // iOS和Android均支持代码控制静音
>                     autoplay: false,
>                     loop: true,
>                 });
>             }
> ```

浏览器WASM是有内存上限的，如果要做抖音的效果的话，需要保证页面只保留2-3个实例并且需要尽可能保证destroy释放内存。

**Comment by hoperyy** [comment]
好的，我先保留 2 个实例试验一下，多谢！

**Comment by ErosZy** [comment]
@hoperyy 如果还有问题可以重新open这个issue，我先关闭了。
