### ISSUE TITLE
Webcodecs hardware decode support?

### ISSUE THREAD

**Issue by fishel-feng** [qiaozi-tech/WXInlinePlayer#95]
The new browser supports Webcodecs API, which can use hardware for video codec, is there any planing to support this?

**Comment by ErosZy** [comment]
Hi @fishel-feng, we have a internel version support WebCodec/WASM/AudioProcessor/AduioWorklet. However, as the work in question conflicts with WXInlinePlayer, it will involve internal confidentiality agreements, so the relevant feature enhancements are not supported on this side for the time being.

我们公司内部版本有一个 WXInlinePlayer 的升级版播放器支持 WebCodec/WASM/AudioProcessor/AudioWorklet 等相关特性，但考虑到涉及内部的工作成果及保密要求，因此 WXInlinePlayer 暂时不会支持相关的特性。

**Comment by fishel-feng** [comment]
好的，感谢回复
